name: Release action
# Call the reusable workflow release-solution-with-inputs.yml
# Release your solution to prod when you create a new release.

on:
  release:
      types: [created]        
permissions:
  contents: write
jobs:
  Release-solution-ALMLab:
    uses: ./.github/workflows/release-solution-to-prod-with-inputs.yml
    with:
      #You can specify the solution name here
      solution_name: ALMLab
      #Update your values here
      BUILD_ENVIRONMENT_URL: https://org797ca272.crm.dynamics.com
      PRODUCTION_ENVIRONMENT_URL: https://org4bdf4cfa.crm.dynamics.com
      CLIENT_ID: 5e14bed2-4033-458e-9bed-56ff1f089306
      TENANT_ID: daa3d854-29bd-4d1a-b704-187329d569d8         
    secrets:
      envSecret: ${{ secrets.PowerPlatformSPN }}
